<?php
/**
 * @file
 * SN Mapping Page
 */


/**
 *  implements hook_menu()
 *  This is to create the AJAX page for the map dropdowns
 */
function snmapping_menu() {
  $items = array();
  $items['admin/snmapping'] = array(
    'title' => 'SN Mapping',
    'page callback' => 'sn_mapping',
    'access arguments' => array('access sn_mapping content'),
    'description' => 'SN Mapping',
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
    );
  return $items;
}


/**
 *  sn_mapping()
 *  This creates the AJAX response to the dropdown selection
 */
function sn_mapping() {

  if (isset($_POST['state'])) {
    $query = db_select('field_data_field_sales_region_state_initial', 't')
               ->fields('t', array('entity_id'))
               ->condition('field_sales_region_state_initial_value', $_POST['state'], '=')
               ->execute()
               ->fetchObject();


    if (isset($query->entity_id)) {
      $nodes = taxonomy_select_nodes($query->entity_id);
      foreach ($nodes as $key => $nid) {
        $node = node_load($nid);
        if ($node->type == 'sales_manager') {

          $img = file_create_url($node->field_sales_photo['und'][0]['uri']);
          print '<img src="' . $img . '" width=100><br>';
          print $node->title . '<br>';
          print $node->field_sales_title['und'][0]['value'] . '<br>';
          print $node->field_sales_cell_phone['und'][0]['value'] . '<br>';
          print $node->field_sales_email['und'][0]['value'] . '<br>';

        }
      }
    }

  }

  if (isset($_POST['nid'])) {
   print printNode($_POST['nid']);
  }


}



function printNode($nid) {
  $node = node_load($nid);
  if (is_object($node)) {
    $return = $node->title . '<br>';
    $return .= $node->field_service_contact['und'][0]['value'] . '<br>';
    $return .= $node->field_service_phone['und'][0]['value'] . '<br>';
    $return .= $node->field_service_email['und'][0]['value'] . '<br>';
    $return .= $node->field_service_website['und'][0]['value'] . '<br>';
  }
  return $return;
}


/**
 *  CTOOLS Panel
 */
function snmapping_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'ctools' && $plugin_type == 'content_types') {
    return 'plugins/' . $plugin_type;
  }
}

/*
 * Implements hook_form_alter
 *
 */
function snmapping_form_alter(&$form, &$form_state, $form_id) {
  if($form_id = 'better_jump_menu') {
    if ($form['#form_id'] != 'views_ui_edit_form') {
      unset($form['#attached']);
    }
  }
  // dpm($form);
}



